vich_uploader:
    db_driver: orm

    mappings:
        postImage:
            uri_prefix: /uploads/post/images
            upload_destination: '%kernel.project_dir%/public/uploads/post/images'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'id' }
